#ifndef TEST_HOST_GPS_CBOR_CODERS_TEST_CODERS_H
#define TEST_HOST_GPS_CBOR_CODERS_TEST_CODERS_H

void test_It_should_encode_gps_coordinates();

void test_It_should_encode_and_decode_gps_coordinates();

#endif //TEST_HOST_GPS_CBOR_CODERS_TEST_CODERS_H
